In [126]:
import numpy as np

In [127]:
from IPython.display import Image
from IPython.core.display import HTML 

# Concept of Neural Networks

In [142]:
# Activation function
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

class NeuralNetwork:   
    # y is the label for the given input while x is the input
    def __init__(self,x,y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1],3) # number of neurons in hidden layer = 3 
        self.weights2 = np.random.rand(3,1)
        self.y = y
        self.output = np.zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input,self.weights1)) # +self.biases1)
        self.layer2 = sigmoid(np.dot(self.layer1,self.weights2)) # +self.biases2)
        return self.layer2
    
    def backprop(self):
        # application of the chain rule to find derivative of the loss function with respect to weights2 and weights1
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        # squared loss function L = (realLabel - outputLabel)²
        d_weights1 = np.dot(self.input.T,  (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))

        # update the weights with the derivative (slope) of the loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2
        
    def train(self, X, y):
        self.input = X
        self.output = y
        self.output = self.feedforward()
        self.backprop()

In [149]:
# Each row is a training example, each column is a feature  [X1, X2, X3]
X=np.array(([1,1,1],[0,1,1],[1,0,1],[0,0,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)

NN = NeuralNetwork(X,y)
for i in range(1000): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
        print ("\n")
  
    NN.train(X, y)

for iteration # 0

Input : 
[[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.81167371]
 [0.78000056]
 [0.78591139]
 [0.74180477]]
Loss: 
0.32583055233690406


for iteration # 100

Input : 
[[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.52257965]
 [0.54302438]
 [0.49015109]
 [0.4761284 ]]
Loss: 
0.242140094318696


for iteration # 200

Input : 
[[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.44539614]
 [0.74866483]
 [0.61123158]
 [0.15612168]]
Loss: 
0.10926548751440018


for iteration # 300

Input : 
[[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.16979296]
 [0.86415188]
 [0.8562819 ]
 [0.05671286]]
Loss: 
0.01778890127703706


for iteration # 400

Input : 
[[1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]
Actual Output: 
[[0.]
 [1

# Feedforward 

In [148]:
# Binary Step Function (activation function)
def binstep(x):
    return int(x>=0)

# Perceptron
x = np.array([1,0,-1])
w = np.array(np.random.rand(3))
# bias term random in (-1,1]
b = np.random.random() *2 -1
y = binstep(np.matmul(x.T,w) + b)

# Defining 'Neuron' Function
print(y)

1


# Concept of Neural Networks 
![title](img/NN.png)
What the NN is actually doing is optimizing an approximated function onto a given data set

# Linear Regression
- approximating the data given with a linear function 
- Perceptron enough (f(x)= wx+b)

# Logistic Regression
- used for binary output 
- fitting a logistic propability function

![title](img/Regression.jpg)

# Types of Machine Learning Problems 

- Classification
- Regression
- Clustering
- Rule Extraction

# Convolution

![title](img/Convolution.png)

# Maxpooling
- picking the maximum value in the filter size
- in the above example with a 3x3 filter size the returned value is 2 

# Flattening

![title](img/Flattening.png)

# Linear and non-linear functions

- The general form of a linear function is y = mx + b.
- non-linear is everything else exceeding the linear definition

# Question: How is non-linearity achieved in neural networks?
- the activation functions introduce non-linearity to the neural network model (sigmoid,tanh)

# Questions
What is ...
Body: -combination of organ systems and tissue types into a single organism  

Organ: -group of tissues which together perform similar functions (organspecific: functional/supportive tissue) 

Tissue: -ensamble of cells with similar function or group function

Cell: -smallest unit of life

Nucleus: -core of a cell surrounded by cytoplasm

DNA(Deoxyribonucleic acid): -two polynuceleotide strands forming the typical helical shape containing AT or CG pairs and a alternating sugar-phosporus backbone structure, contains the gentic information of the organism (cytosine[C],thymine[T],adenine[A],guanine[G])

RNA(Ribonucleic acid): -single stranded, transporting genetic information (coded building plan of proteins), important for protein synthesis

Proteins: -polypeptides build with amino-acids with a vast function field like transporting signal-molecules etc.

Cytoplasm: -everything inside the cell membrane except of the nucleus


![title](img/Central-Dogma.png)